name: Release Version

on:
  push:
    tags:
      - "release-v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.11.1.1413'
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Cache All The Things
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.npm
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: cljdeps-${{ hashFiles('deps.edn', 'package.json') }}
      - name: Install node dependencies
        run: npm install
      - name: Install karma cli globally
        run: npm install -g karma-cli
      - name: Run Tests
        run: clojure -T:build ci :snapshot false
      - name: Deploy Release
        run: clojure -T:build deploy :snapshot false
        env:
          CLOJARS_PASSWORD: ${{secrets.DEPLOY_TOKEN}}
          CLOJARS_USERNAME: ${{secrets.DEPLOY_USERNAME}}
